### ISSUE TITLE
Shift from Heroku to DO

### ISSUE THREAD

**Issue by bhawesh96** [cribbl/miteb-backend#14]
1. Configure `travis.yml`. Encrypt and use environment, config files and deploy keys.
2. Add `.eslintignore` to suppress CI warnings
3. Configure the server for staging and prod

Refer frontend

**Comment by rsarky** [comment]
On discussion with @bhawesh96 it was decided that the deployment platform should be Heroku.
The application has been deployed to heroku :tada:
